### ISSUE TITLE
Read & write repository

### ISSUE THREAD

**Issue by ddenysov** [somnambulist-tech/accounts-service-skeleton#1]
https://github.com/somnambulist-tech/accounts-service-skeleton/blob/3bdfcde5803c7fabd6982bf6431161931e972a40/src/Users/Infrastructure/Persistence/Repositories/UserRepository.php#L12

Hello,

If I understand correct we have Commands and Queries to split read and write operations. But we still using the same Repository class for read and write operations. So I don't understand why do we need Commands and Queries in this case?

**Comment by dave-redfern** [comment]
This project uses the Command / Query Responsibility Separation (CQRS) pattern for all data access. That pattern is where the use of commands and queries comes from. This allows for, not only the, separation of read and write operations, but the data model that is used for each of those. Generally: querying does not have the same requirements as writing changes. Whenever you write changes you want those to always be "valid" and to only allow valid changes, but the query side you just want a representation "now" or some other summary form.

In this specific example:

The UserRepository is used by commands that need to operate on the User model. It is deliberately bare with only the minimum of functionality necessary for this role. For example: you can only find by ID, store, and delete. There are no find/search or other methods defined. If you check the query handlers (or check for code usages) you will see this class is never used.

Instead the query side uses view models for the data - not the UserRepository. As such the domain models are never returned and used in the API responses; in fact the User model does not have getters for most of the internal state as it is not intended to be used for presentation. The query side could avoid all use of objects entirely and return plain arrays instead, but I chose to use objects that are more geared toward presentation purposes i.e. they are read-only, cannot be modified, saved, and can have any additional helper methods for generating view state - though more complex representations would be better served by querying for them specifically.

I'm not sure I am explaining myself very well, so please let me know if you want more clarification on any particular point!

**Comment by ddenysov** [comment]
Thank you for clarification. I still have some additional question. Why we cant use Domain model with getters (such as aggregates for example) and pass them to serializers or view presenters. In your example you are using Laravel models to load data directly from database. I can see some problems here:
1. Domain model may contain some business logic that not stored in database (for example discounts calculations)
2. We have direct dependency on database and Laravel. What if we would like to change data storage (to NoSQL for example). Or Laravel introduce major update without back capability. 

I'm sorry if I asking stupid questions. I just want to understand this topic better.

**Comment by dave-redfern** [comment]
> Thank you for clarification. I still have some additional question. Why we cant use Domain model with getters (such as aggregates for example) and pass them to serializers or view presenters.

You _can_ but that does not mean you _should_. The domain models in a DDD project are all about controlling data, ensuring that changes to the domain happen in an orderly and valid manner. If you start adding accessors and presentational logic to that it detracts from the core API of making changes. If you pass to a presenter, then you need accessors and you risk having logic that infers domain state - and that is not a great position to be in. The very worst thing that can happen is that the presenter starts to include business logic that it shouldn't.

So you can go that route - it is up to you but be aware of what the pros and cons. Everything is a trade-off and you may decide that having separate view models is too much to deal with, but that would be up to you to decide.

Personally I really do not like having a read API on my write models. If you take a look at the User model you can see that the API is very clean, it only exposes the operations you can perform, there's no ambiguity. I like that it is this clean. Adding accessors would IMHO confuse the purpose, and potentially become more of a problem when what you really want is not the write model but some other representation of it e.g. summary details or a composition of various other bits. Why load the domain models that need to be fully loaded to be valid, if what you want can be done by using SQL and various group by / count / window functions?

> In your example you are using Laravel models to load data directly from database. I can see some problems here:

Nope it's not Laravel 😉 I use my read-models library that is inspired by Laravels Eloquent. read-models is for read-only representations of data / querying though I want to improve it quite a bit for the next version. read-models uses Doctrine DBAL under-the-hood and is intentionally very limited, but it does work quite well for views. I originally built it to be passed to Twig for rendering, it tends to lose some of it's utility when used in a pure API context.

> 1. Domain model may contain some business logic that not stored in database (for example discounts calculations)

In an ideal situation the domain models are created without thinking about how the data is persisted since they are all about the business problem. Your domain models should be agnostic of persistence; hence the need for infrastructure layers and why the repositories are defined as interfaces and not concrete implementations.

Taking the example of a discount: this implies applying a discount to a basket. The basket would be a specific bounded context and an aggregate root in its own right. Therefore it will have behaviour and almost certainly some form of storage since you need to be able to make changes to it as it will have a lifecycle. The fact a discount has been applied would _have_ to be recorded in the domain model and therefore would require persistence with the rest of the basket - it would not be a transient piece of information.

A more complete example for applying a discount could be:

 * make request to apply a discount to a basket
 * controller dispatches a command that has the discount code + basket ID
 * command handler fetches the discount and the basket
 * discount and basket objects are passed to a price calculator domain service
 * price calculator runs the logic to apply the discount and total the basket
 * the controller queries for the updated basket information and returns a response

> 2. We have direct dependency on database and Laravel. What if we would like to change data storage (to NoSQL for example). Or Laravel introduce major update without back capability.

Easy: don't use the read-models library and implement whatever querying you want instead. If you want to use MongoDB then you can use Doctrine ODM and pure Mongo client to read it, or maybe you need to pull data from an API. This is entirely fine, there is nothing that says you _have_ to use my read-models. In fact I will use pure Doctrine DBAL and return arrays of data instead of objects, or call APIs to fetch data and those might be converted to objects. It all depends on the specific use case and what you want to achieve.

> I'm sorry if I asking stupid questions. I just want to understand this topic better.

There's no such thing as a stupid question! 😁 Especially when you are new to a topic.

Domain Driven Design covers a huge amount of ideas and it can be quite confusing. There are many things that can leave you scratching your head or at first glance don't seem to make sense. I am still learning myself, and I freely admit I do not follow it precisely and some things I still struggle with.

So ask as many questions as you want - it will help me to figure things out too.

**Comment by ddenysov** [comment]
Thanks for the detailed answer. I'll need to read about read and write models. :)
